id: opecha:P000100                                          # Catalog
initial_creation_type: tsadra-epub                          # Catalog

source_metadata:                                            # Exporting
  title: ༄༅། །ཕྱག་ཆེན་སྔོན་འགྲོ་བཞི་སྦྱོར་དང་དངོས་གཞིའི་ཁྲིད་རིམ་མདོར་བསྡུས་ངེས་དོན་སྒྲོན་མེ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  subtitle:
  authors:
    - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས། །
  collection-title:
  publisher:
  images:
    cover-image: assets/images/LEK-PHI-001.jpg
    publication-data-image: assets/images/LEK-PHI-001.jpg
    content-images-path: assets/images/content/

layers:                                                     # Editing
- Chapter
- Citation
- Sabche
- Yigchung
